language: python

python:
    - 2.6
    - 2.7
    - 3.2
    - 3.3

env:
    global:
        - PIP_WHEEL_COMMAND="pip install --find-links http://wheels.astropy.org/ --find-links http://wheels2.astropy.org/ --use-wheel --upgrade --use-mirrors"
    matrix:
        - NUMPY_VERSION=1.7.1 SETUP_CMD='test'

matrix:
    include:
        # try alternate Numpy versions
        - python: 2.7
          env: NUMPY_VERSION=1.6.2 SETUP_CMD='test'
        - python: 2.7
          env: NUMPY_VERSION=1.5.1 SETUP_CMD='test'
        - python: 3.2
          env: NUMPY_VERSION=1.6.2 SETUP_CMD='test'
        - python: 2.7
          env: NUMPY_VERSION=1.7.1 SETUP_CMD='cov'

before_install:

   # Install the pip that supports wheel
   - pip install setuptools --upgrade
   - pip install pip --upgrade
   - pip install wheel

   - sudo apt-get update -qq
   - sudo apt-get install -qq python-numpy

install:
   - export PYTHONIOENCODING=UTF8 # just in case
   - $PIP_WHEEL_COMMAND "Cython>=0.18" --use-mirrors
   - $PIP_WHEEL_COMMAND "numpy==$NUMPY_VERSION" --use-mirrors
   - pip install git+http://github.com/astropy/astropy.git#egg=astropy
   - if [[ $SETUP_CMD == cov ]]; then pip install pytest --use-mirrors; fi
   - if [[ $SETUP_CMD == cov ]]; then pip install pytest-cov --use-mirrors; fi
   - if [[ $SETUP_CMD == cov ]]; then pip install coveralls --use-mirrors; fi

script:
   - if [[ $SETUP_CMD == test ]]; then python setup.py test ; fi
   - if [[ $SETUP_CMD == cov ]]; then py.test --cov sedfitter; fi

after_success:
  - if [[ $SETUP_CMD == cov ]]; then coveralls; fi
